# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    "*.md",
    ".devcontainer/**",
    "*.properties",
    "*.kts",
    "**/*.kts",
    "**/*.xml",
    "**/*.kt",
    "**/*.conf",
    "**/*.yaml",
    "**/*.imports"
]
SPDX-FileCopyrightText = "2024 Robert Winkler"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "gradle/**",
    "gradlew",
    "gradlew.bat"
]
SPDX-FileCopyrightText = "Copyright 2015 the original author or authors."
SPDX-License-Identifier = "Apache-2.0"