#
# SPDX-FileCopyrightText: Robert Winkler
#
# SPDX-License-Identifier: Apache-2.0
#

spring:
  application:
    name: chat-agent    # Service name for tracing (appears in Langfuse UI as the source service)

management:
  tracing:
    sampling:
      probability: 1.0    # Sample 100% of requests for full tracing (adjust in production as needed)
  observations:
    annotations:
      enabled: true       # Enable @Observed (if you use observation annotations in code)

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
    logging:
      enabled: true
  propagators:
    - tracecontext
  instrumentation:
    micrometer:
      enabled: true

arc:
  ai:
    clients:
      - id: GPT-4o
        model-name: GPT35T-1106
        api-key: dummy
        client: langchain4j-azure
        url: https://gpt4-uk.openai.azure.com
    tools:
      scraper:
        url: "http://localhost:9099/scraper"
      #devices:
      #  url: "https://plugfest.webthings.io/.well-known/wot"
      #  isDirectory: true
      #  securityScheme: "bearer"

wot:
  servient:
    security:
      credentials:
        "[https://plugfest.webthings.io]":
          type: "bearer"
          token: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjE1OWM4MzhlLWYxZmItNGE3ZC1iZDY2LTBlNmI1ZDZjNWVhMCJ9.eyJyb2xlIjoidXNlcl90b2tlbiIsImlhdCI6MTczMjI5MjczNSwiaXNzIjoiaHR0cHM6Ly9wbHVnZmVzdC53ZWJ0aGluZ3MuaW8ifQ.CpQ5MLSygmCJFS6yz4Xdf0xyImwqBWvNfKNZPX9DNHjyjuq5wzq0mWurSu11wR-BwnZ2lnFcIId3ytfbo9hBwg"
    websocket:
      server:
        enabled: true
        host: localhost
        port: 8181
    http:
      server:
        enabled: false
        host: localhost
        port: 9080
    mqtt:
      server:
        enabled: false
        host: localhost
        port: 54801
        clientId: wot-servient
      client:
        enabled: false
        host: localhost
        port: 54801
        clientId: wot-client
